// dummy_data.dart
final List<Map<String, String>> employees = [
    {
      'name': 'John Doe',
      'gender': 'Male',
      'email': 'john@example.com',
      'designation': 'Software Engineer',
      'phone': '+1 123-456-7890',
      'address': '123 Main St, Anytown, USA',
      'joinDate': '2022-01-15',
    },
    {
      'name': 'Jane Smith',
      'gender': 'Female',
      'email': 'jane@example.com',
      'designation': 'Product Manager',
      'phone': '+1 987-654-3210',
      'address': '456 Oak Ave, Another City, USA',
      'joinDate': '2021-11-01',
    },
    {
      'name': 'Michael Brown',
      'gender': 'Male',
      'email': 'michael.brown@example.com',
      'designation': 'Data Scientist',
      'phone': '+1 555-0123',
      'address': '789 Pine St, Sample City, USA',
      'joinDate': '2023-03-10',
    },
    {
      'name': 'Emily Johnson',
      'gender': 'Female',
      'email': 'emily.johnson@example.com',
      'designation': 'UI/UX Designer',
      'phone': '+1 555-4567',
      'address': '234 Elm St, Sampletown, USA',
      'joinDate': '2022-06-22',
    },
    {
      'name': 'David Wilson',
      'gender': 'Male',
      'email': 'david.wilson@example.com',
      'designation': 'Software Developer',
      'phone': '+1 555-8910',
      'address': '345 Maple St, Example City, USA',
      'joinDate': '2021-12-15',
    },
    {
      'name': 'Sophia Garcia',
      'gender': 'Female',
      'email': 'sophia.garcia@example.com',
      'designation': 'Marketing Specialist',
      'phone': '+1 555-6789',
      'address': '678 Cedar St, Another Town, USA',
      'joinDate': '2022-09-05',
    },
    {
      'name': 'James Martinez',
      'gender': 'Male',
      'email': 'james.martinez@example.com',
      'designation': 'System Analyst',
      'phone': '+1 555-2345',
      'address': '456 Birch Rd, Sample City, USA',
      'joinDate': '2020-05-25',
    },
    {
      'name': 'Olivia Rodriguez',
      'gender': 'Female',
      'email': 'olivia.rodriguez@example.com',
      'designation': 'Project Coordinator',
      'phone': '+1 555-5432',
      'address': '321 Spruce St, Exampleville, USA',
      'joinDate': '2023-01-11',
    },
    {
      'name': 'William Lee',
      'gender': 'Male',
      'email': 'william.lee@example.com',
      'designation': 'DevOps Engineer',
      'phone': '+1 555-6781',
      'address': '987 Ash Ave, Sampletown, USA',
      'joinDate': '2023-04-20',
    },
    {
      'name': 'Ava Perez',
      'gender': 'Female',
      'email': 'ava.perez@example.com',
      'designation': 'HR Manager',
      'phone': '+1 555-0987',
      'address': '543 Fir St, Another City, USA',
      'joinDate': '2021-08-30',
    },
    {
      'name': 'Lucas Young',
      'gender': 'Male',
      'email': 'lucas.young@example.com',
      'designation': 'Business Analyst',
      'phone': '+1 555-3456',
      'address': '159 Willow Ct, Sample City, USA',
      'joinDate': '2022-02-14',
    },
    {
      'name': 'Mia Thompson',
      'gender': 'Female',
      'email': 'mia.thompson@example.com',
      'designation': 'Graphic Designer',
      'phone': '+1 555-8765',
      'address': '753 Cypress Ln, Exampleville, USA',
      'joinDate': '2020-07-19',
    },
];
